---
ID: 1ce3b36c-9b0c-4eb5-a996-bfcb4eaa5287
Parent: eb2e4ffd-2761-4653-b052-26a64d385227
Template: a87a00b1-e6db-45ab-8b54-636fec3b5523
Path: /sitecore/layout/Placeholder Settings
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {5C547D4E-7111-4995-95B0-6B561751BF2E}
    {C3B037A0-46E5-4B67-AC7A-A144B962A56F}
- ID: 9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4
  # __Read Only
  Value: 1
- ID: dec8d2d5-e3cf-48b6-a653-8e69e2716641
  # __Security
  Value: ar|sitecore\Sitecore Client Developing|pd|+item:delete|+item:create|+item:rename|+item:read|+item:write|pe|+item:create|
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T120204Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Indstillinger for placeholder
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115752Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Platzhaltereinstellungen
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20080110T095800
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115351Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: プレースホルダー設定
