---
ID: 49d86313-493d-4054-acc9-d68ad6b09332
Parent: 7ce9fda0-e6c1-4495-9740-9944656e893b
Template: 087dcaf1-4778-4849-99b4-599b901dbe09
Path: /sitecore/system/Settings/Buckets/Search Types/Site
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  # __Icon
  Value: Network/32x32/earth.png
- ID: 1635fb77-9af7-4c2f-bace-81d0c8462e18
  # WebMethod
  Value: ItemBucket.asmx/GetSites
- ID: 759a7bd8-c40a-475e-a650-d7c9dfd89cd0
  # Field
  Value: site
- ID: 9d2e8c51-5921-498a-bff6-d6aa99d3eeee
  # Control Type
  Value: {8428729B-93B4-4A6B-8E78-603D5986FBD3}
- ID: a434e593-d2b2-4591-8916-74564962d6d5
  # Icon
  Value: /sitecore/shell/Applications/Buckets/images/site.png
- ID: d5ca4991-ea12-4fbd-b797-1de976a79540
  # Client Side Hook
  Value: normal
- ID: d94cdb6a-d0fd-42f2-8370-0346a17b3d5a
  # Name
  Value: site
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T120214Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Hjemmeside
    - ID: cc084d53-fa58-4591-b7c7-20e7a60c8a4a
      # Display Text
      Value: Søg ved hjælp af hjemmeside
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115803Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Site
    - ID: cc084d53-fa58-4591-b7c7-20e7a60c8a4a
      # Display Text
      Value: Suchen anhand von Site
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20111103T104900
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: cc084d53-fa58-4591-b7c7-20e7a60c8a4a
      # Display Text
      Value: Search by site
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115400Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: サイト
    - ID: cc084d53-fa58-4591-b7c7-20e7a60c8a4a
      # Display Text
      Value: サイトを指定して検索
