---
ID: 25e4831a-c3c0-4b3d-9972-5bc67a822e4b
Parent: 31a34c19-a686-4cf4-838d-e522d01d54bf
Template: 6d1cd897-1936-4a3a-a511-289a94c2a7b1
Path: /sitecore/system/Dictionary/ExperienceExplorer/Preset/Viewer/PresetViewerEnvironment
SharedFields:
- ID: 580c75a8-c01a-4580-83cb-987776ceb3af
  # Key
  Value: PresetViewerEnvironment
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T120208Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Miljø
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: PresetViewerEnvironment
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115755Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Umgebung
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: VoreinstellungViewerUmgebung
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20130129T071819
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Environment
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115352Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: 環境
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: プリセット ビューアー環境
