---
ID: c8c6fa48-4956-4691-bc27-98a57564f25f
Parent: 8c3c48fe-7edf-40c1-bcba-041a2a3a424d
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/User Defined/Demo Site/Renderings/SPA Rendering/Single Page Application
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150921T032045Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
