---
ID: aa9420ce-e147-4466-a71d-b8ae70af6d0a
Parent: ff0bc016-2d01-4f55-a020-ef6fc2fe7559
Template: 664e5035-eb8c-4ba1-9731-a098fcc9127a
Path: /sitecore/system/Settings/Rules/Insert Options/Rules/Social Applications
SharedFields:
- ID: fa307b86-da2a-44bd-887d-e2057cdb4948
  # Rule
  Type: Rules
  Value: |
    <ruleset>
      <rule uid="{FC37B972-3B37-4BC0-A741-89F1734FDE94}">
        <conditions>
          <condition id="{7D5DA661-BEF9-441C-B1F7-D80DE3E0972F}" uid="04BEA2E3115B49AABB378C5EC9F30CA1" itemid="{7D1340C0-7C54-4437-BF3D-E1D65C2EC661}" />
        </conditions>
        <actions>
          <action id="{918FFCF0-F9E1-4DB6-A191-3EFA5A91C583}" uid="107EFCB6052C4DA58EAD60956E4E60DC" insertoptionid="{8015BB44-6D50-4C56-980B-435A77AA5B09}" />
        </actions>
      </rule>
    </ruleset>
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T120243Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Sociale applikationer
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115832Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Social Applications
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20120216T110700
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115414Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: ソーシャル アプリケーション
