---
ID: 32182414-9d49-4e3c-9060-fd1656fde745
Parent: 17d73079-b727-4967-a3a0-59068dc85bb8
Template: 6d1cd897-1936-4a3a-a511-289a94c2a7b1
Path: /sitecore/system/Dictionary/ExperienceExplorer/Settings/Editor/SettingsEditorTitle
SharedFields:
- ID: 580c75a8-c01a-4580-83cb-987776ceb3af
  # Key
  Value: SettingsEditorTitle
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T120211Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Indstillinger
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: SettingsEditorTitle
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115758Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Einstellungen
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: EinstellungenEditorTitel
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20130225T091840
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: Settings
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150812T115353Z
    - ID: 2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e
      # Phrase
      Value: 設定
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      # __Owner
      Value: sitecore\admin
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 設定エディター タイトル
